### ISSUE TITLE
[Security] Workflow update-majorver.yml is using vulnerable action nowactions/update-majorver

### ISSUE THREAD

**Issue by igibek** [nowactions/update-majorver#207]
The workflow update-majorver.yml is referencing action nowactions/update-majorver using references v1. However this reference is missing the commit [bb62b5eb2400464ad98d708f96305c4c309de253](https://github.com/nowactions/update-majorver/commits/bb62b5eb2400464ad98d708f96305c4c309de253) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by nownabe** [comment]
Thanks! I released a fixed version as `v1`.
